### ISSUE TITLE
点击login跳转到存储评论的 repo上

### ISSUE THREAD

**Issue by goodluckforever** [imsun/gitment#10]
hexo 如题

**Comment by wa-ri** [comment]
我的点击login之后会就会跳转到 OAuth Application里填的callback URL，不知道是不是
```
id: ' location.href', 
owner: 'wa-ri',
repo: 'comments',
```
这些没填写正确

**Comment by s2117402** [comment]
我也出现这个问题了

**Comment by imsun** [comment]
登录后跳转的地址是在 OAuth Application 里填的 Callback URI。这个是 OAuth 的正常流程。

**Comment by wa-ri** [comment]
@imsun  很感谢你的回复。我的问题是没有登录成功，仅仅是跳转到了那个Callback URI。后来发现是我没有初始化评论，但是我没有出现那个初始化的按钮，直接显示的是Error: Comments Not Initialized

**Comment by imsun** [comment]
你需要登录 owner 的账号才会显示初始化的按钮。其他人的账号不会显示初始化按钮。
