### ISSUE TITLE
总是提示 [object XMLHttpRequestProgressEvent]

### ISSUE THREAD

**Issue by Chaaang** [imsun/gitment#100]
不管是我自己搭建的 还是别人的，，总会提示这个。然后就无法登陆了。。别人的不登录的话还能看见评论

**Comment by Chaaang** [comment]
https://gh-oauth.imsun.net/ 这个域名的证书失效了，朋友。。所以完全被拦截。。导致不能登录

**Comment by werner-wiki** [comment]
我遇到了类似的问题，总提示：[object ProgressEvent]。

**Comment by sunyazhou13** [comment]
求解决方式

**Comment by lucasjinreal** [comment]
弃用gitment，使用gitalking

**Comment by creasy2010** [comment]
弃用gitment，使用gitalking  是最终解决方法??? 还有人知道 .
