### ISSUE TITLE
点击初始化提示validation failed?

### ISSUE THREAD

**Issue by Napoleon-Jm** [imsun/gitment#11]
如题，控制台日志如下：
api.github.com/repos/Napoleon-Jm/comment-repo/issues:1 POST https://api.github.com/repos/Napoleon-Jm/comment-repo/issues 422 (Unprocessable Entity)

Napoleon-Jm 是我的 GitHub ID，comment-repo 为存储 comments 的 repo.
请问，是我哪里配置错了吗？

**Comment by Napoleon-Jm** [comment]
已经解决了，原来要在 comment-repo 中手动建立一个 Issue。希望可以稍微改善:)

**Comment by yaykids** [comment]
validation failed是怎么解决的

**Comment by tidyjiang8** [comment]
@Napoleon-Jm  
**同求！validation failed是怎么解决的?**

**Comment by YummyLau** [comment]
在 themes\next\layout\_third-party\comments 目录下修改gitments.swig，找到以下代码修改
```
      function renderGitment(){
        var gitment = new {{CommentsClass}}({
-           id: window.location.pathname,
+           id: '{{ page.date }}',
            owner: '{{ theme.gitment.github_user }}',
            repo: '{{ theme.gitment.github_repo }}',
            {% if theme.gitment.mint %}
            lang: "{{ theme.gitment.language }}" || navigator.language || navigator.systemLanguage || navigator.userLanguage,
            {% endif %}
```
之后重新hexo g -d就ok了，请保证没有浏览器缓存。

**Comment by ismumu** [comment]
配置项，id: window.location.href,    默认的是这个
但是issue的标签label有50个字符的长度限制。如果你字符串太多久会导致validation failed,
