### ISSUE TITLE
422 Error: Validation Failed

### ISSUE THREAD

**Issue by FrontendSophie** [imsun/gitment#114]
今天改了一下category的名字，发现分类下的文章都需要重新initialize了，应该是地址不对了就把之前的issue关掉了。重新登陆之后initialize， 却报错弹框Error: Validation Failed，issues API 报错HTTP code 422 Unprocessable Entity，想请教一下这种情况如何解决？

**Comment by maplecumt** [comment]
有可能是id的名字太长了。把document.location.href修改成page.title或者别的文章唯一id就可以了，参考http://xichen.pub/2018/01/31/2018-01-31-gitment/

**Comment by FrontendSophie** [comment]
谢谢，改成了window.location.pathname，已经可以了。

**Comment by Sogrey** [comment]
记录，我也遇到，但是我的问题不是label字符超过50个，而是标题中包含了英文半角的`,` 可以改成中文逗号，希望有帮到后来人。

https://github.com/Sogrey/Sogrey.github.io/issues/28#issuecomment-570901237

**Comment by Sogrey** [comment]
记录，我也遇到，但是我的问题不是label字符超过50个，而是标题中包含了英文半角的`,` 可以改成中文逗号，希望有帮到后来人。

https://github.com/Sogrey/Sogrey.github.io/issues/28#issuecomment-570901237
