### ISSUE TITLE
JekyII主题的PJax链接下会报Uncaught ReferenceError: Gitment is not defined

### ISSUE THREAD

**Issue by chucheng92** [imsun/gitment#127]
<script src="https://imsun.github.io/gitment/dist/gitment.browser.js"></script>肯定是引入的。正常访问相应页面没问题，pjax下会无限加载，出不来页面。

**Comment by sariabiha** [comment]
https://github.com/imsun/gitment/issues/6

**Comment by sariabiha** [comment]
<a href=" rf wrinkle removL"> https://advance-esthetic.us/rf-facial-machines</a>
javascript:;
