### ISSUE TITLE
请教：直接把代码复制到generate后的index中，deploy后，出现一点错误

### ISSUE THREAD

**Issue by EmmaW8** [imsun/gitment#13]
![default](https://cloud.githubusercontent.com/assets/16148104/25513952/9b73f666-2c0b-11e7-8cdd-5de378891634.png)

我是直接把
```
<div id="container"></div>
<link rel="stylesheet" href="https://imsun.github.io/gitment/style/default.css">
<script src="https://imsun.github.io/gitment/dist/gitment.browser.js"></script>
<script>
var gitment = new Gitment({
  id: '页面 ID', // 可选。默认为 location.href
  owner: '你的 GitHub ID',
  repo: '存储评论的 repo',
  oauth: {
    client_id: '你的 client ID',
    client_secret: '你的 client secret',
  },
})
gitment.render('container')
</script>
```
复制到我生成的public文件夹里的index.html中的，我不知道是不是这样处理？？
结果就如上图所示。
不知该怎么解决。
话说我已经安装的gitment，但是并不知道怎么用，是要在markdown文件里写函数吗？？

**Comment by EmmaW8** [comment]
实例：https://emmaw8.github.io/Emma.github.io/2017/04/16/Holland-Flower-Town/

**Comment by EmmaW8** [comment]
补充：
我自己无法评论，别人也无法评论。

并没有找到初始化按钮在哪里

**Comment by imsun** [comment]
https://github.com/EmmaW8/Emma.github.io/blob/7698a2f05fdd22f9abf5742fdbef04b1a6a7d9a2/2017/04/16/Holland-Flower-Town/index.html#L489

这个地方的 `id`，要么填文章 ID，要么留空。

https://github.com/EmmaW8/Emma.github.io/blob/7698a2f05fdd22f9abf5742fdbef04b1a6a7d9a2/2017/04/16/Holland-Flower-Town/index.html#L491

这个地方的 `repo` 要填你存储评论用的 repo 名。比如 'Emma.github.io'

**Comment by EmmaW8** [comment]
You are right!
That's a perfect answer!
