### ISSUE TITLE
用chrome浏览器登陆评论出现了问题

### ISSUE THREAD

**Issue by bluetianx** [imsun/gitment#135]
当我用chrome浏览器打开网页 并登陆github评论时候，一直卡在了 Loading comments... ，
并且页面弹出了一个[object ProgressEvent] 通知窗口 ，我用firefox没有问题的

**Comment by sunyazhou13** [comment]
我的也是

**Comment by codegitz** [comment]
我的也是，楼主解决了吗

**Comment by bluetianx** [comment]
没有，我换成 来比力了
