### ISSUE TITLE
页面 URL 较长时无法初始化评论 

### ISSUE THREAD

**Issue by beginor** [imsun/gitment#149]
点击 `Initialize Comments` 按钮， 提示 `Error: Validation Failed` ， 但是在已经初始化评论的页面进行回复是正常的。

尝试在对应的github代码库中手工创建评论进行分析，发现：

- gitment 为对应的问题创建两个标签， 一个是 gitment ， 一个是页面的 URL 
- github 问题的标签长度限制为 50 个字符， 但是 URL有时比较长， 会超过这个限制

希望能改进一下。

**Comment by heropoo** [comment]
#116 请看这个issue

**Comment by beginor** [comment]
🙏
