### ISSUE TITLE
有关gitment初始化的问题

### ISSUE THREAD

**Issue by butan2333** [imsun/gitment#150]
我的博客每次刷新文章页面都要重新初始化评论，而且每次初始化后的issue都可以评论，但刷新后就会不见==
猜想是因为可以新建issue但读不到issue。
可能原因是把域名换了，但OAUTH中的和hexo站点的三个URL都改成新的了http://www.refrain.site/
有谁有解决方案吗==谢谢

**Comment by Lengsir** [comment]
我看了一下，并没有问题啊

**Comment by butan2333** [comment]
抱歉的确没有问题了・_・，很奇怪当时初始化的时候每次刷新都要重新init来着
