### ISSUE TITLE
评论登录的时候，登录成功会跳转到blog首页是什么原因啊  ？

### ISSUE THREAD

**Issue by Gzbox** [imsun/gitment#160]
评论登录的时候，登录成功会跳转到blog首页是什么原因啊     怎么解决？

**Comment by ada-hs** [comment]
我也是这样的情况，你解决了么

**Comment by Gzbox** [comment]
@ada-hs   解决了  是以为md文档标题的问题，有空格等特殊符号，在授权登录后编译的结果和之前不同，导致会回到首页，  建议md 文档的名称不要使用汉字，使用英文，不要有空格等特殊符号。修正后就解决了

**Comment by Litreily** [comment]
@Gzbox 我也遇到了，但是我的标题均以英文及连字符命名，不存在楼上所述问题，所以还有其它问题。另外，之前很长一段时间都没出现此类问题，近期出现的，不知为何

**Comment by realsinair** [comment]
我的md文件名有中文的也有纯英文的，但是均出现此问题。

**Comment by LuhangRui** [comment]
这个问题的原因是login那个链接里的`redirect_uri`和`callback_url`匹配不上，所以会往`callback_url`跳转

1.可以F12检查一下login的链接对比developer Apps 中的`Authorization callback URL`

2.跳转回首页的时候链接里是带有错误信息的，看一下，解决它

具体参见我的博客[gitment初始化评论跳回博客首页](https://ergou.fun/posts/47886.html)
