### ISSUE TITLE
改域名后gitment看不到了，失效了

### ISSUE THREAD

**Issue by wardseptember** [imsun/gitment#171]

**Comment by wardseptember** [comment]
我的gitment在我更改域名后就失效了，是啥问题？请教一下，谢谢了。
http://wardseptember.me/

**Comment by Mabbs** [comment]
改域名的话，oauth上的home page也要改

**Comment by HackettYu** [comment]
应该是 callback URL [https://imsun.net/posts/gitment-introduction/](url)

**Comment by sariabiha** [comment]
[](<a href="mini rf skin tightening lifting machine factories"> https://advance-esthetic.us/rf-facial-machines</a>
)
