### ISSUE TITLE
点击Issue里显示undefined

### ISSUE THREAD

**Issue by xiaohao890809** [imsun/gitment#19]
......./undefined

**Comment by imsun** [comment]
未初始化的评论就会显示 undefined。

如果不是这个原因请贴配置代码。

**Comment by linonetwo** [comment]
我也遇到这个问题
```html
<script>
	var gitment = new Gitment({
		id: '{{ page.date }}',
		owner: 'linonetwo',
		repo: 'linonetwo.github.io',
		oauth: {
			client_id: '8a658374212177e63e4c',
			client_secret: '...',
		},
	})
	gitment.render('gitmentcontainer')
</script>
```
这是文章地址 http://onetwo.ren/%E5%89%8D%E7%AB%AF%E6%8F%92%E4%BB%B6%E7%B3%BB%E7%BB%9F%E8%AE%BE%E8%AE%A1/
这是之前有的评论地址
https://github.com/linonetwo/linonetwo.github.io/issues/3
但现在点 issue 地址会跳到
http://onetwo.ren/%E5%89%8D%E7%AB%AF%E6%8F%92%E4%BB%B6%E7%B3%BB%E7%BB%9F%E8%AE%BE%E8%AE%A1/undefined
