### ISSUE TITLE
一点小设想

### ISSUE THREAD

**Issue by wrfly** [imsun/gitment#2]
是不是可以在发布文章的时候触发一个 “新建issue” 的动作，然后将这个issue页面挂到博客下面去，这样大家也都不用登陆授权了，只要登陆了github就可以评论。

实质上还是访问的github的issue页面，但是看到的就是在文章下面了。

**Comment by imsun** [comment]
在发布时自动开 issue 的 API 我之后会提供。（其实已经做好了，只是好多东西还没没文档化。）

将 issue 页面放到博客下是做不到的，因为 GitHub 的安全策略禁止将它的页面显示在 iframe 内。

**Comment by wrfly** [comment]
了解
