### ISSUE TITLE
请教 如何初始化评论

### ISSUE THREAD

**Issue by desnbo** [imsun/gitment#20]
我的评论框处的 `Issue Page` 指向 当前文章 url 下的 ./undefined,并提示 `Error: Not Found`
而不是指定仓库下的 issues ,

**Comment by desnbo** [comment]
解决了,仓库名直接是: gitment 而不是仓库地址

**Comment by raoenhui** [comment]
我也遇到这个问题了，仓库名也写对了，大神是怎么解决的呀
