### ISSUE TITLE
能否做到不同文章的评论分开

### ISSUE THREAD

**Issue by sigusr1** [imsun/gitment#23]
目前不同文章的评论会混在一起，能否做到分开

**Comment by yanm1ng** [comment]
每篇文章更改 document.title 就可以 新建 issue 了吧

**Comment by Desgard** [comment]
必然可以啊。修改 id 即可。
用我 blog 中的评论给你[举例](https://github.com/Desgard/desgard.github.com/blob/guardia-v4.0/source/_includes/comments.html#L30)

**Comment by yanm1ng** [comment]
```javascript
var gitment = new Gitment({
    id: document.title
});
```
目前我是这么来做的

**Comment by imsun** [comment]
评论是与文章 id 对应的。只要文章 id 填对就不会混在一起。
