### ISSUE TITLE
建议添加 URL 尾部参数屏蔽

### ISSUE THREAD

**Issue by MoeYi** [imsun/gitment#42]
在加入 Gitment 的页面进行 OAuth 后， CallBack 会在页面 URL 末端加上一个 ?code= 的 OAuth Key ，此时进行初始化评论 Issue 标签末尾也会带参数。并且从微信朋友圈打开文章末尾会带上 ?from=timeline 参数，相同页面加入不同参数获取到的评论结果不同，望支持屏蔽末尾参数。

![8 m p z uqzbab a0 judp4](https://user-images.githubusercontent.com/18461360/27584950-c03d4ffc-5b6c-11e7-9820-40212454ae9e.png)

**Comment by imsun** [comment]
使用 URL 做文章 id 是为了用一个通用的唯一标识符方便示例，实际上应该是由使用者自行指定文章 id。

URL 包含的协议信息和域名信息其实都不该有，因为不同协议和域名的 URL 对应的可能是同一篇文章。一些 query 参数也是不该传入的，因为不同参数（如分页参数）对应的也可能是同一篇文章。这些信息在 Gitment 内部无法判断是否需要，只能传入什么就用什么。

不过很奇怪的是我在 OAuth 结束后会通过 `replaceState` 去掉那个 code，不知道为什么你的还在。请问有没有具体的浏览器信息和使用代码？

**Comment by MoeYi** [comment]
现在似乎没有问题了，但是应该有一个过滤功能，例如 https://example.com/post.html 和 https://example.com/post-2.html 是同一篇文章使用同样的评论

**Comment by imsun** [comment]
这个应该是使用者在 Gitment 外做的，两个页面都传入 'post' 作为 id。对 Gitment 来说 id 就是个字符串，不会作任何语义上的判断。
