### ISSUE TITLE
GitBook如何引入Gitment?

### ISSUE THREAD

**Issue by shenshanlaoyuan** [imsun/gitment#49]
如题，GitBook没有评论很不爽，如何接入Gitment评论呢？求大神指点！

**Comment by huangjj27** [comment]
gitbook.io本身有自己的`discussion`系统, 可以用作评论系统, 具体方法为点击鼠标悬浮段落右边出现的`+`按钮

**Comment by Honghe** [comment]
@huangjj27 若想再引入gitment，是否可行？

**Comment by huangjj27** [comment]
比较难, 因为在gitbooks.io上的文章的源码都是由官方的服务器生成的, 想要通过植入代码的方式引入gitment应该不会凑效.
