### ISSUE TITLE
如何将带www的URL和不带www的URL视为同一URL？

### ISSUE THREAD

**Issue by cshuaimin** [imsun/gitment#55]
如果 www.example.com/article 和 example.com/article 指向的是同一页面，如何让它们共享评论？类似的还有 www.example.com/article#more 有无井号也是同一页面。

**Comment by GeekaholicLin** [comment]
`id:window.location.pathname`

#46

**Comment by cshuaimin** [comment]
非常感谢

**Comment by GeekaholicLin** [comment]
@cshuaimin 不过有一个问题就是域名不同并不能共享。按照我的理解，一个域名对应一个application，一个application不能拥有多个域名。但是按照上面的配置"有无井号"确实可以看成一个"页面"。

**Comment by GeekaholicLin** [comment]
不过迁移的时候（比如更换域名）应该比较简单（没试过，按道理来讲的话），只需要在自己的github更改application的域名即可。

**Comment by cshuaimin** [comment]
@GeekaholicLin 我按照你的办法改了后不管有没有www都可以共享评论了，至于完全不同的域名就不得而知了:joy:

**Comment by GeekaholicLin** [comment]
_(:зゝ∠)_这都行。解决了就更好 😃

**Comment by tiexo** [comment]
@GeekaholicLin  这个id:window.location.pathname是在哪里设置？

**Comment by cshuaimin** [comment]
看你是怎么配置的了，你要是直接改的模板文件，就去模板里找下面这段：
```javascript
      var gitment = new Gitment({
        owner: 'xx',
        repo: 'xx',
        oauth: {
          client_id: 'xx',
          client_secret: 'xx',
          },
        id: window.location.pathname,
      })
```
设置相应id的值。
如果不是，那就去看看主题的 _config.yml 文件

**Comment by tiexo** [comment]
我刚刚就是这样设置的，结果所有的文章都需要重新初始化评论了，而且初始化后生成的链接都是一样的...
可以在我gitment仓库的issue区看看，有个被关闭的就是刚刚测试的失败品，然后我又改回来了
 ------------------
来自 魅族 PRO 6 Plus


------------------ Original ------------------

**Comment by cshuaimin** [comment]
id变了，肯定是要重新初始化的。但初始化后生成的链接都是一样的？不应该是以文章链接区分吗？
@GeekaholicLin 坐等大神

**Comment by tiexo** [comment]
![s70730-230151](https://user-images.githubusercontent.com/8164505/28754642-a114e174-750e-11e7-9ace-4c19be958f7f.jpg)
![s70730-230139](https://user-images.githubusercontent.com/8164505/28754644-a79dbd18-750e-11e7-8555-9d86d3a2add4.jpg)

这是修改前后的变化，链接直接替换成window.location.pathname了

**Comment by cshuaimin** [comment]
你该不会给window.location.pathname加引号了吧:joy:

**Comment by tiexo** [comment]
应该没有吧...明天我再试试😤😤😤
 ------------------
来自 魅族 PRO 6 Plus


------------------ Original ------------------

**Comment by GeekaholicLin** [comment]
@cshuaimin 并不是大神😂。

@tiexo 我印象文档是说以`label`为唯一id进行请求的，但是你的lable为`window.location.pathname`，所以很可能你写成字符串了。。

**Comment by tiexo** [comment]
解决了，多谢两位。

**Comment by hxhb** [comment]
@cshuaimin 修改为`window.location.pathname`之后两个不同的域名是可以共享gitment的评论的。
