### ISSUE TITLE
怎么我初始化了一遍在所有的页面上都能用?然后评论共享了?

### ISSUE THREAD

**Issue by Dedsecr** [imsun/gitment#60]
rt

**Comment by adymilk** [comment]
你点一下你评论框右上方的 issue page ，看下跳转过去的URL

**Comment by Dedsecr** [comment]
跳转到了我第一次初始化的页面的issue page

**Comment by adymilk** [comment]
Your page ID 默认不填写试下

**Comment by Dedsecr** [comment]
请问在哪里

**Comment by adymilk** [comment]
id: '页面 ID', // 可选。默认为 location.href

**Comment by Dedsecr** [comment]
没有用

**Comment by tiexo** [comment]
看了下你的label为 `location.href`，而不是链接
应该是写法错误了，检查下空格，引号之类的

**Comment by Dedsecr** [comment]
是否因为我是在
![image](https://user-images.githubusercontent.com/25794491/29007515-4db177fc-7b37-11e7-89b5-e6ba9266c980.png)中引用的代码,而不是在.md文章中引用的?

**Comment by Dedsecr** [comment]
我把id改了,可以用了,谢谢大家
