### ISSUE TITLE
一个页面的多个锚会对应多个issue

### ISSUE THREAD

**Issue by tidyjiang8** [imsun/gitment#62]
你好，
如题，一个页面，如果有多个锚，会对应多个issue，这个能不能修改一下？
比如我的同一个页面，我初始化了两次（这本来就不对了），然后生成了两个issue：
https://github.com/tidyjiang8/esp-idf-zh/issues/6
https://github.com/tidyjiang8/esp-idf-zh/issues/7
这两个issue对应的commits为：
http://iot-fans.xyz/2017/08/09/esp32/esp-idf-zh/#more
http://iot-fans.xyz/2017/08/09/esp32/esp-idf-zh/

**Comment by GeekaholicLin** [comment]
#46

**Comment by tidyjiang8** [comment]
@GeekaholicLin  
非常感谢
不过本人太小白了，没找到 `id: document.location.href`，求指点.
我的gitment的配置文件在这里：　[https://github.com/tidyjiang8/zephyrproject.cn/blob/master/themes/navy/layout/partial/comment.swig](https://github.com/tidyjiang8/zephyrproject.cn/blob/master/themes/navy/layout/partial/comment.swig)

**Comment by tidyjiang8** [comment]
已经找到了，在 https://imsun.github.io/gitment/dist/gitment.browser.js 这里面，应该知道怎么做了，再次感谢~
