### ISSUE TITLE
评论第一次初始化成功，在进到其它的文章里面的评论就初始化失败了？

### ISSUE THREAD

**Issue by ifelseboyxx** [imsun/gitment#70]
第一次能登录成功，接下来就一直是失败的了，需要退出去重新进来，谁知道原因吗？

![](https://user-images.githubusercontent.com/24642787/30193297-f4c9b5b6-9411-11e7-801d-9c55e9816796.png)

![](https://user-images.githubusercontent.com/24642787/30193261-da2e4262-9411-11e7-8bda-cc9e174554cc.png)

**Comment by ifelseboyxx** [comment]
而且我自己的电脑上不会出现那个  Error 信息，会出现 重新登录的按钮

![](https://user-images.githubusercontent.com/24642787/30193387-634bd2da-9412-11e7-80a8-e5235849d72e.png)

**Comment by WenmuZhou** [comment]
我也碰到了
